/**
 * The starting catalog from Plan §3, edited together in Phase 0. Ids are stable
 * slugs so the quick row, combos and tests can refer to them.
 */
import { Reward, Task } from '@/schemas'
import type { Category, Freq, Reward as RewardT, Task as TaskT } from '@/schemas'

export const SEED_IDS = {
  cookDinner: 'task-kitchen-cook-dinner',
  makeBreakfast: 'task-kitchen-make-breakfast',
  makeLunch: 'task-kitchen-make-lunch',
  handWash: 'task-kitchen-hand-wash',
  pots: 'task-kitchen-pots',
  pans: 'task-kitchen-pans',
  trays: 'task-kitchen-trays',
  knives: 'task-kitchen-knives',
  blender: 'task-kitchen-blender',
  bigStuff: 'task-kitchen-big-stuff',
  dryPutAway: 'task-kitchen-dry-put-away',
  counters: 'task-kitchen-counters',
  dishwasherLoad: 'task-kitchen-dishwasher-load',
  dishwasherUnload: 'task-kitchen-dishwasher-unload',
  trash: 'task-kitchen-trash',
  sink: 'task-kitchen-sink',
  bottles: 'task-kitchen-bottles',
  sterilize: 'task-kitchen-sterilize',
  stove: 'task-kitchen-stove',
  coffeeClean: 'task-kitchen-coffee-clean',
  descale: 'task-kitchen-descale',
  dishwasherClean: 'task-kitchen-dishwasher-clean',
  fridge: 'task-kitchen-fridge',
  freezer: 'task-kitchen-freezer',
  mealPlan: 'task-kitchen-meal-plan',
  groceries: 'task-kitchen-groceries',
  putGroceries: 'task-kitchen-put-groceries',
  washCycle: 'task-laundry-wash',
  dry: 'task-laundry-dry',
  fold: 'task-laundry-fold',
  socks: 'task-laundry-socks',
  putAway: 'task-laundry-put-away',
  sheets: 'task-laundry-sheets',
  cribBedding: 'task-laundry-crib-bedding',
  iron: 'task-laundry-iron',
  lint: 'task-laundry-lint',
  dryerClean: 'task-laundry-dryer-clean',
  washerClean: 'task-laundry-washer-clean',
  pickUp: 'task-floors-pick-up',
  vacuumAll: 'task-floors-vacuum-all',
  vacuumRoom: 'task-floors-vacuum-room',
  mop: 'task-floors-mop',
  dust: 'task-floors-dust',
  computerTable: 'task-floors-computer-table',
  bedroomShelves: 'task-floors-bedroom-shelves',
  cleanBathroom: 'task-bathroom-clean',
  toilet: 'task-bathroom-toilet',
  bathSink: 'task-bathroom-sink',
  shower: 'task-bathroom-shower',
  drain: 'task-bathroom-drain',
  bathroomFloor: 'task-bathroom-floor',
  towels: 'task-bathroom-towels',
  diaperBin: 'task-bathroom-diaper-bin',
  sanitaryBin: 'task-bathroom-sanitary-bin',
  bathKids: 'task-kids-bath',
  babyFood: 'task-kids-baby-food',
  babyFoodGear: 'task-kids-baby-food-gear',
  bedtime: 'task-kids-bedtime',
  nightWake: 'task-kids-night-wake',
  kidsClothes: 'task-kids-clothes',
  organizeToys: 'task-kids-toys',
  drawings: 'task-kids-drawings',
  daycareBag: 'task-kids-daycare-bag',
  kidsAdmin: 'task-kids-admin',
  kidsBooks: 'task-kids-books',
  plants: 'task-home-plants',
  balcony: 'task-home-balcony',
  storage: 'task-home-storage',
  bulky: 'task-home-bulky',
  cleanWindows: 'task-home-windows',
  windowsBalcony: 'task-home-windows-balcony',
  windowsTerrace: 'task-home-windows-terrace',
  windowsBedroom: 'task-home-windows-bedroom',
  medicineCabinet: 'task-home-medicine-cabinet',
  tvTable: 'task-home-tv-table',
  computerTableSort: 'task-home-computer-table',
  mail: 'task-admin-mail',
  handledAThing: 'task-admin-handled',
  carWash: 'task-car-wash',
  carCarpets: 'task-car-carpets',
  carTrunk: 'task-car-trunk',
  kidToys: 'task-kid-toys',
  kidHamper: 'task-kid-hamper',
  kidTable: 'task-kid-table',
  kidPlant: 'task-kid-plant',
  kidSocks: 'task-kid-socks',
} as const

/** What the quick row shows before it has learned anything (Plan §5.5). */
export const DEFAULT_QUICK_ROW: readonly string[] = [SEED_IDS.pots, SEED_IDS.counters, SEED_IDS.trash]

type Row = [id: string, name: string, category: Category, points: number, freq: Freq, extra?: Partial<TaskT>]

const ROWS: Row[] = [
  [SEED_IDS.cookDinner, 'Cook dinner', 'kitchen', 6, 'daily'],
  [SEED_IDS.makeBreakfast, 'Make breakfast', 'kitchen', 3, 'daily'],
  [SEED_IDS.makeLunch, 'Make lunch', 'kitchen', 4, 'daily'],
  [SEED_IDS.handWash, 'Hand-wash dishes', 'kitchen', 0, 'daily'],
  [SEED_IDS.pots, 'Pots', 'kitchen', 2, 'daily', { parentId: SEED_IDS.handWash }],
  [SEED_IDS.pans, 'Pans / wok', 'kitchen', 2, 'daily', { parentId: SEED_IDS.handWash }],
  [SEED_IDS.trays, 'Oven trays / casserole dishes', 'kitchen', 2, 'adhoc', { parentId: SEED_IDS.handWash }],
  [SEED_IDS.knives, 'Knives + cutting boards', 'kitchen', 1, 'daily', { parentId: SEED_IDS.handWash }],
  [SEED_IDS.blender, 'Blender / mixer parts', 'kitchen', 2, 'adhoc', { parentId: SEED_IDS.handWash }],
  [
    SEED_IDS.bigStuff,
    'Big stuff (stock pot, rack, bins, lunchboxes)',
    'kitchen',
    1,
    'adhoc',
    { parentId: SEED_IDS.handWash },
  ],
  [SEED_IDS.dryPutAway, 'Dry + put away hand-washed items', 'kitchen', 1, 'daily'],
  [SEED_IDS.counters, 'Clean kitchen counters', 'kitchen', 3, 'daily'],
  [SEED_IDS.dishwasherLoad, 'Load + start dishwasher', 'kitchen', 2, 'daily'],
  [SEED_IDS.dishwasherUnload, 'Unload dishwasher', 'kitchen', 2, 'daily'],
  [SEED_IDS.trash, 'Take out trash / recycling', 'kitchen', 2, 'daily'],
  [SEED_IDS.sink, 'Clear food from sink + empty strainer', 'kitchen', 2, 'daily'],
  [SEED_IDS.bottles, 'Wash baby bottles / pump parts', 'kitchen', 3, 'daily'],
  [SEED_IDS.sterilize, 'Sterilize bottles', 'kitchen', 1, 'daily'],
  [SEED_IDS.stove, 'Clean stove / hob', 'kitchen', 3, 'weekly'],
  [SEED_IDS.coffeeClean, 'Clean coffee machine', 'kitchen', 2, 'weekly'],
  [SEED_IDS.descale, 'Descale coffee machine', 'kitchen', 3, 'monthly'],
  [SEED_IDS.dishwasherClean, 'Clean dishwasher (filter, arms, seal)', 'kitchen', 3, 'monthly'],
  [SEED_IDS.fridge, 'Fridge cleanout + wipe', 'kitchen', 4, 'biweekly', { intervalDays: 14 }],
  [SEED_IDS.freezer, 'Clean freezer (defrost + wipe)', 'kitchen', 5, 'quarterly'],
  [SEED_IDS.mealPlan, 'Meal plan for the week', 'kitchen', 3, 'weekly'],
  [SEED_IDS.groceries, 'Grocery shopping (big run)', 'kitchen', 5, 'weekly'],
  [SEED_IDS.putGroceries, 'Put groceries away', 'kitchen', 2, 'weekly'],
  [SEED_IDS.washCycle, 'Wash cycle (sort + load + start)', 'laundry', 2, 'daily'],
  [SEED_IDS.dry, 'Move to dryer / hang to dry', 'laundry', 2, 'daily'],
  [SEED_IDS.fold, 'Fold a load', 'laundry', 3, 'daily'],
  [SEED_IDS.socks, 'Pair socks + sort underwear', 'laundry', 1, 'daily'],
  [SEED_IDS.putAway, 'Put folded clothes away', 'laundry', 2, 'daily'],
  [SEED_IDS.sheets, 'Change bed sheets (one bed)', 'laundry', 3, 'weekly'],
  [SEED_IDS.cribBedding, 'Wash + change crib bedding', 'laundry', 3, 'weekly'],
  [SEED_IDS.iron, 'Iron (per session)', 'laundry', 3, 'adhoc'],
  [SEED_IDS.lint, 'Clean dryer lint filter', 'laundry', 1, 'weekly'],
  [SEED_IDS.dryerClean, 'Clean dryer (condenser, tank, drum)', 'laundry', 3, 'monthly'],
  [SEED_IDS.washerClean, 'Clean washing machine', 'laundry', 3, 'monthly'],
  [SEED_IDS.pickUp, 'Pick everything up off the floor', 'floors', 3, 'daily'],
  [SEED_IDS.vacuumAll, 'Vacuum whole home', 'floors', 5, 'weekly', { intervalDays: 3 }],
  [SEED_IDS.vacuumRoom, 'Vacuum one room', 'floors', 2, 'adhoc', { intervalDays: 1 }],
  [SEED_IDS.mop, 'Wet-mop floors', 'floors', 5, 'weekly', { intervalDays: 5 }],
  [SEED_IDS.dust, 'Dust shelves and surfaces', 'floors', 3, 'weekly'],
  [SEED_IDS.computerTable, 'Clean computer table', 'floors', 2, 'weekly'],
  [SEED_IDS.bedroomShelves, 'Clean bedroom shelves', 'floors', 2, 'weekly'],
  [SEED_IDS.cleanBathroom, 'Clean bathroom', 'bathroom', 0, 'weekly', { comboBonus: 2, intervalDays: 7 }],
  [SEED_IDS.toilet, 'Toilet', 'bathroom', 4, 'weekly', { parentId: SEED_IDS.cleanBathroom }],
  [SEED_IDS.bathSink, 'Sink + mirror + counter', 'bathroom', 2, 'weekly', { parentId: SEED_IDS.cleanBathroom }],
  [SEED_IDS.shower, 'Shower / tub', 'bathroom', 4, 'weekly', { parentId: SEED_IDS.cleanBathroom }],
  [SEED_IDS.drain, 'Clear shower drain', 'bathroom', 4, 'weekly', { parentId: SEED_IDS.cleanBathroom }],
  [SEED_IDS.bathroomFloor, 'Bathroom floor (mop)', 'bathroom', 2, 'weekly'],
  [SEED_IDS.towels, 'Replace towels', 'bathroom', 1, 'weekly'],
  [SEED_IDS.diaperBin, 'Empty diaper bin', 'bathroom', 2, 'weekly'],
  [SEED_IDS.sanitaryBin, 'Empty sanitary bin', 'bathroom', 2, 'weekly'],
  [SEED_IDS.bathKids, 'Bath the kids', 'kids', 4, 'daily'],
  [SEED_IDS.babyFood, 'Make baby food', 'kids', 4, 'weekly', { intervalDays: 4 }],
  [SEED_IDS.babyFoodGear, 'Wash baby food containers + gear', 'kids', 2, 'daily'],
  [SEED_IDS.bedtime, 'Bedtime routine', 'kids', 4, 'daily'],
  [SEED_IDS.nightWake, 'Night feed / wake-up', 'kids', 3, 'daily'],
  [SEED_IDS.kidsClothes, "Sort kids' clothes (outgrown, seasons)", 'kids', 5, 'monthly'],
  [SEED_IDS.organizeToys, 'Organize toys', 'kids', 3, 'weekly'],
  [SEED_IDS.drawings, "Organize kids' drawings", 'kids', 3, 'monthly'],
  [SEED_IDS.daycareBag, 'Prep daycare bag', 'kids', 2, 'daily'],
  [SEED_IDS.kidsAdmin, 'Doctor / daycare admin', 'kids', 3, 'adhoc'],
  [SEED_IDS.kidsBooks, "Sort kids' books", 'kids', 2, 'monthly'],
  [SEED_IDS.plants, 'Water plants', 'home', 2, 'weekly'],
  [SEED_IDS.balcony, 'Clean balcony', 'home', 5, 'monthly'],
  [SEED_IDS.storage, 'Organize storage room', 'home', 8, 'quarterly'],
  [SEED_IDS.bulky, 'Big recycling / bulky waste', 'home', 4, 'adhoc'],
  [SEED_IDS.cleanWindows, 'Clean windows', 'home', 0, 'quarterly', { comboBonus: 2, intervalDays: 90 }],
  [SEED_IDS.windowsBalcony, 'Balcony windows', 'home', 3, 'quarterly', { parentId: SEED_IDS.cleanWindows }],
  [SEED_IDS.windowsTerrace, 'Terrace windows', 'home', 3, 'quarterly', { parentId: SEED_IDS.cleanWindows }],
  [SEED_IDS.windowsBedroom, 'Bedroom windows', 'home', 2, 'quarterly', { parentId: SEED_IDS.cleanWindows }],
  [SEED_IDS.medicineCabinet, 'Sort medicine cabinet', 'home', 3, 'quarterly'],
  [SEED_IDS.tvTable, 'Sort TV table', 'home', 2, 'monthly'],
  [SEED_IDS.computerTableSort, 'Sort computer table', 'home', 2, 'monthly'],
  [SEED_IDS.mail, 'Sort mail, pay bills', 'admin', 2, 'weekly'],
  [SEED_IDS.handledAThing, 'Handled a thing', 'admin', 2, 'adhoc'],
  [SEED_IDS.carWash, 'Car wash', 'car', 5, 'monthly'],
  [SEED_IDS.carCarpets, 'Car carpets (vacuum + wash)', 'car', 4, 'monthly'],
  [SEED_IDS.carTrunk, 'Car trunk cleanout', 'car', 3, 'monthly'],
  [SEED_IDS.kidToys, 'Put toys in the box', 'kid', 1, 'daily', { forRole: 'kid' }],
  [SEED_IDS.kidHamper, 'Dirty clothes in the hamper', 'kid', 1, 'daily', { forRole: 'kid' }],
  [SEED_IDS.kidTable, 'Help set the table', 'kid', 1, 'daily', { forRole: 'kid' }],
  [SEED_IDS.kidPlant, 'Water one plant', 'kid', 1, 'weekly', { forRole: 'kid' }],
  [SEED_IDS.kidSocks, 'Match socks from the laundry', 'kid', 2, 'weekly', { forRole: 'kid' }],
]

export function seedTasks(now: Date, by: string): TaskT[] {
  return ROWS.map(([id, name, category, points, freq, extra], i) =>
    Task.parse({ v: 1, id, name, category, points, freq, sort: i, updatedAt: now, updatedBy: by, ...extra }),
  )
}

type RewardRow = [id: string, name: string, cost: number, kind: RewardT['kind'], commitment?: string]

const REWARDS: RewardRow[] = [
  ['reward-coffee-out', '1h coffee out, alone', 20, 'solo', 'Solo with both kids for 1h'],
  ['reward-hobby', '2h hobby, door closed, phone off', 35, 'solo', 'Solo with both kids for 2h'],
  ['reward-sleep-in', 'Sleep in on a weekend', 40, 'solo', 'Morning shift with both kids'],
  ['reward-gym', 'Solo gym / run / walk (90 min)', 30, 'solo', 'Solo with both kids'],
  ['reward-bath', 'Long bath, door locked', 15, 'solo', 'Handle everything for 45 min'],
  ['reward-evening-out', 'Evening out with friends', 60, 'solo', 'Full evening + bedtime solo'],
  ['reward-chore-free', 'Chore-free day', 50, 'solo', 'Covers the daily loop that day'],
  ['reward-pastry', 'Fancy coffee / pastry delivered', 10, 'treat'],
  ['reward-movie', 'Pick the movie, no veto', 10, 'treat'],
  ['reward-takeout', 'Takeout dinner', 25, 'treat'],
  ['reward-wishlist', 'That small thing from the wishlist', 30, 'treat'],
  ['reward-babysitter', 'Babysitter evening', 100, 'pooled'],
  ['reward-empty-house', 'Weekend morning with the house empty', 40, 'pooled'],
  ['reward-kid-story', 'Pick the bedtime story', 5, 'kid'],
  ['reward-kid-breakfast', 'Choose Saturday breakfast', 5, 'kid'],
  ['reward-kid-playground', '15 min extra playground', 5, 'kid'],
  ['reward-kid-stickers', 'Sticker sheet', 5, 'kid'],
]

export function seedRewards(now: Date, by: string): RewardT[] {
  return REWARDS.map(([id, name, cost, kind, commitment]) =>
    Reward.parse({ v: 1, id, name, cost, kind, commitment, updatedAt: now, updatedBy: by }),
  )
}
